version: "3.8"

services:
  accounts:
    image: accounts
    ports:
      - "8085:8080"
    depends_on:
      config:
        condition: service_healthy
    links:
      - config
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://config:8080/
    networks:
      - ansis-network

  loans:
    image: loans
    ports:
      - "8082:8080"
    networks:
      - ansis-network

  cards:
    image: cards
    ports:
      - "8083:8080"
    networks:
      - ansis-network

  helloworld:
    image: helloworld
    ports:
      - "8084:8080"
    networks:
      - ansis-network

  config:
    image: config
    ports:
      - "8888:8080"
    networks:
      - ansis-network
    healthcheck:
      test: curl --fail http://localhost:8080/accounts/dev || exit 1
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 5s


networks:
  ansis-network: