version: "3.8"

services:
  accounts:
    image: accounts
    ports:
      - "8089:8080"
    depends_on:
      config:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    links:
      - config
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 180s
    environment:
      - spring.profiles.active=prod
      - spring.application.name=accounts
      - spring.config.import=configserver:http://config:8080/
      - eureka.instance.preferIpAddress=true
      - eureka.client.fetchRegistry=true
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8080/eureka/
      - management.info.env.enabled=true
      - info.app.name=accounts
      - info.app.description=AccountsDescription
      - info.app.version=1.0.0
      - endpoints.shutdown.enabled=true
      - management.endpoint.shutdown.enabled=true
    networks:
      - ansis-network2

  accounts1:
    image: accounts
    ports:
      - "8090:8080"
    depends_on:
      config:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    links:
      - config
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 180s
    environment:
      - spring.profiles.active=prod
      - spring.application.name=accounts
      - spring.config.import=configserver:http://config:8080/
      - eureka.instance.preferIpAddress=true
      - eureka.client.fetchRegistry=true
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8080/eureka/
      - management.info.env.enabled=true
      - info.app.name=accounts
      - info.app.description=AccountsDescription
      - info.app.version=1.0.0
      - endpoints.shutdown.enabled=true
      - management.endpoint.shutdown.enabled=true
    networks:
      - ansis-network2

  eurekaserver:
    image: eurekaserver
    ports:
      - "9001:8080"
    depends_on:
      config:
        condition: service_healthy
    links:
      - config
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 180s
    healthcheck:
      test: curl --fail http://localhost:8080/ || exit 1
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 5s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://config:8080/
    networks:
      - ansis-network2

  loans:
    image: loans
    ports:
      - "8086:8080"
    networks:
      - ansis-network2
    environment:
      - spring.profiles.active=prod
      - spring.application.name=loans
      - spring.config.import=configserver:http://config:8080/
      - eureka.instance.preferIpAddress=true
      - eureka.client.fetchRegistry=true
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8080/eureka/
      - management.info.env.enabled=true
      - info.app.name=loans
      - info.app.description=LoansDescription
      - info.app.version=1.0.0
      - endpoints.shutdown.enabled=true
      - management.endpoint.shutdown.enabled=true
    depends_on:
      config:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy

  cards:
    image: cards
    ports:
      - "8087:8080"
    networks:
      - ansis-network2
    environment:
      - spring.profiles.active=prod
      - spring.application.name=cards
      - spring.config.import=configserver:http://config:8080/
      - eureka.instance.preferIpAddress=true
      - eureka.client.fetchRegistry=true
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8080/eureka/
      - management.info.env.enabled=true
      - info.app.name=cards
      - info.app.description=CardsDescription
      - info.app.version=1.0.0
      - endpoints.shutdown.enabled=true
      - management.endpoint.shutdown.enabled=true
    depends_on:
      config:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy

  helloworld:
    image: helloworld
    ports:
      - "8088:8080"
    networks:
      - ansis-network2
    environment:
      - spring.profiles.active=prod
      - spring.application.name=helloworld
      - spring.config.import=configserver:http://config:8080/
      - eureka.instance.preferIpAddress=true
      - eureka.client.fetchRegistry=true
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8080/eureka/
      - management.info.env.enabled=true
      - info.app.name=HelloWorld
      - info.app.description=HelloWorldDescription
      - info.app.version=1.0.0
      - endpoints.shutdown.enabled=true
      - management.endpoint.shutdown.enabled=true
    depends_on:
      config:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy

  config:
    image: config
    ports:
      - "8889:8080"
    networks:
      - ansis-network2
    healthcheck:
      test: curl --fail http://localhost:8080/accounts/dev || exit 1
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 5s


networks:
  ansis-network2: